Style denunciations
kvlsndkf/project pull request #104
Opened 2022-06-24 01:01 UTC by emillienicole

http://localhost/project/private/adm/pages/denunciation/list-denunciation.page.php

2022-06-26 01:35 UTC, Ti-Alves approved these changes

2022-06-26 01:38 UTC, gustavodesantana approved these changes

2022-06-26 19:03 UTC, hmiranda99 requested changes
## Pontos vistos

### Card
- O espaçamento entre as labels dentro do card estão diferentes e o espaçamento entre os cards estão diferentes também

*Como está*
![image](https://user-images.githubusercontent.com/79329906/175829931-c6fd5cc3-82f2-4683-8cad-d04027d76d57.png)

*Como é*
![image](https://user-images.githubusercontent.com/79329906/175829937-9297d8df-ebd8-44a6-9ce5-6cd33f62005b.png)

2022-06-27 03:50 UTC, hmiranda99 approved these changes

2022-06-27 03:51 UTC, kvlsndkf approved these changes

2022-06-27 03:53 UTC, merged