Reparos Gerais
kvlsndkf/project pull request #108
Opened 2022-06-24 14:45 UTC by Ti-Alves

## O que foi feito:
### Páginas que o Ranking foi adicionado: 
- Feed de Preferências
- Resultado da Pesquisa
- Perfil
- Listagem de quem estou Seguindo
- Listagem dos meus Seguidores

### Páginas que as Preferências foram adicionadas:
- Feed de Preferências (eu diria irônico)
- Resultado da Pesquisa
- Listagem de quem estou Seguindo
- Listagem dos meus Seguidores

### Ajustes Gerais:
- Eliminação dos Desafios
- Adição do botão de sair no topo da página
- Estilização dos botões de Denunciar e Sair no Perfil do Aluno
- Adição do Botão para sair na versão Mobile (Através do Perfil do Próprio aluno, como várias redes sociais)
- Eliminação das Notificações
- Eliminação da label Fale Conosco no footer
- Adição do link no logo do Heelp
- Remoção do card de Dar um Heelp no Feed de Preferências
- Adição do botão de Pedir um Heelp em todas as versões Mobile
- Texto com o nome do curso na Listagem de Preferências truncado
- Imagens da NavBar alinhadas entre si

## Quem não revisar o bicho papão vai buscar hoje a noite
[
![Captura de tela 2022-06-24 114448](https://user-images.githubusercontent.com/100052769/175559717-f64c896c-92f1-493b-a15d-70afdcd90226.png)
](http://localhost/project/private/student/pages/home/home.page.php)

2022-06-24 15:14 UTC, emillienicole reviewed
<h3>Preferências</h3>
- Item da sidebar `Seguindo` está sem link e sem o hover
- A @hmiranda99 havia peço para eu diminuir a distância entre o **"Para você"** e as **preferências**  e a distância do botão de `pedir help` no feed na minha PR, aí no feed ele está com espaçamento menor que o restante, para ser mais prático eu recomendaria retirar o espaçamento que eu havia feito já que a maioria está com a outra, mas como foi uma mudança pedida pela Helena, eu invoco ela pra decidir isso
- Os ícones da sidebar que foram arrumados nas demais telas, está torto nas preferências
- Menu responsivo está com o ícone do feed roxinho

<h3>Responsividade</h3>
- O menu responsivo está com a opção de notificação
- Acho que está em cima da hora e também não mostraríamos na apresentação, mas tem alguma forma do usuário mobile acessar as preferências?

2022-06-24 17:50 UTC, Palominha approved these changes

2022-06-25 00:01 UTC, hmiranda99 requested changes
## Pontos vistos

### Ranking
- O ranking na página dos detalhes da questão está com o número sem estilo
![image](https://user-images.githubusercontent.com/79329906/175749674-b82a3fa0-5ddb-498b-a9b8-63bcd001b7b4.png)

- Página de preferências está com o divider branco 
![image](https://user-images.githubusercontent.com/79329906/175749782-8c9eed02-6394-4289-a3da-8b6ecb139077.png)

##
### Botão de sair
- No perfil não precisa ter mais o botão de sair, já que temos um grandão agora
![image](https://user-images.githubusercontent.com/79329906/175749875-add852f6-c73c-425e-b247-7aa31551e107.png)

2022-06-25 21:37 UTC, emillienicole approved these changes

2022-06-25 21:44 UTC, gustavodesantana approved these changes

2022-06-26 13:50 UTC, garcia235 approved these changes

2022-06-26 14:21 UTC, Gih08 approved these changes

2022-06-27 02:54 UTC, hmiranda99 approved these changes

2022-06-27 02:54 UTC, merged