Reparos da Landing Page
kvlsndkf/project pull request #109
Opened 2022-06-24 23:29 UTC by Ti-Alves

...

2022-06-26 12:48 UTC, emillienicole reviewed
De tudo que citou, o que não está indo é o link da navbar "Fale Conosco" não estar abrindo o modal

2022-06-26 13:50 UTC, gustavodesantana approved these changes

2022-06-26 13:50 UTC, emillienicole approved these changes

2022-06-26 13:50 UTC, garcia235 approved these changes

2022-06-26 18:39 UTC, hmiranda99 requested changes
## Pontos vistos

### Navbar
- Quando clico no fale consoco da navbar, o modal não aparece.

2022-06-27 02:57 UTC, hmiranda99 approved these changes

2022-06-27 02:57 UTC, merged