Página de Etecs
kvlsndkf/project pull request #13
Opened 2022-05-04 13:17 UTC by hmiranda99

2022-05-19 12:22 UTC, emillienicole requested changes
**Pontos vistos**

- O texto do sobre continua desaparecendo na edição;
- Está cadastrando, editando e excluindo sem problemas!

2022-05-19 13:12 UTC, Ti-Alves reviewed
Pontos revisados e nenhum problema foi visto

- algo que notei foi que quando vc clica nos links(fb, github e linkedin) estao indo para o projeto, como se fossem um arquivo dentro do projeto:

![image](https://user-images.githubusercontent.com/100052769/169300189-3a4ef6aa-d2e9-499e-92ed-2d17cfb7d719.png)

- outra coisa foi que eu posso colocar qualquer coisa nos links, seja ela um site real ou não, como visto acima

Como tudo isso é detalhe, meus parabéns pq é bastante coisa, ta maravilhoso!✨

2022-05-19 13:53 UTC, gustavodesantana reviewed
Após a etec criada, quando vc vai editar o "Sobre" dela, ele n tem limites de markdowns que abrem

![image](https://user-images.githubusercontent.com/79333823/169554208-50e53b35-de14-4550-8d52-4297608424dd.png)

e a partir das segundas caixas em diante vem com uma opcção "markdown" desabilitada 

![image](https://user-images.githubusercontent.com/79333823/169554336-5c0e193d-986d-4c39-82a0-5efb52429123.png)

e quando você habilita ele disponibiliza novas funções

![image](https://user-images.githubusercontent.com/79333823/169554488-b7ad0ea6-196a-489e-9185-8afd6631a837.png)

2022-05-20 17:41 UTC, Palominha approved these changes
Revisado e Aprovado!!

2022-05-21 03:16 UTC, emillienicole approved these changes
Funcionando perfeitamente! Arrasou, parabéns!

2022-05-21 14:19 UTC, Ti-Alves approved these changes
revisado e aprovado!

2022-05-21 14:52 UTC, garcia235 approved these changes

2022-05-21 14:55 UTC, merged