Feat/register teacher
kvlsndkf/project pull request #15
Opened 2022-05-11 01:11 UTC by emillienicole

🔗 localhost/project/private/adm/pages/register/register-teacher/form-register-teacher.page.php 🔗

Estilização da página feita do zero de acordo com o protótipo.

> Observações: No protótipo a parte de "nenhum arquivo selecionado" estava em bold, mas com o tamanho da letra, ficou um efeito estranho, parecendo que o bold deixava apertado, de difícil visualização, então coloquei o medium.

2022-05-12 05:13 UTC, Ti-Alves approved these changes

2022-05-12 12:09 UTC, hmiranda99 requested changes
## Pontos vistos

### Seta de voltar
- A seta de voltar não está com link.

### Cadastro
- O professor não está sendo cadastrado, quando aperta no botão cadastrar não acontece nada.

### Hover botões
- É melhor para a padronização, que o hover do botão seja igual ao da página de login.

### Botão reset
- Não sei como foi feita a parte para aparecer o nome da foto escolhida, mas o botão reset não está mais tirando a foto, só tira o nome do professor.

### Reponsividade
- P-E-R-F-E-I-T-A :tada:

*Ficou muito lindo, parabéns!* 🐱

2022-05-13 01:32 UTC, hmiranda99 approved these changes
👇🏼 
biurifu
🧇 
sem palavras
🦘

2022-05-13 01:48 UTC, Gih08 approved these changes

2022-05-13 02:27 UTC, Ti-Alves approved these changes

2022-05-13 02:33 UTC, MayaraPereira17 approved these changes

2022-05-13 02:36 UTC, merged