Painel de Registro - ADM
kvlsndkf/project pull request #16
Opened 2022-05-12 13:04 UTC by Ti-Alves

Tarefa para a criação da tela `registration-panel-page.php` para a seleção do que será cadastrado.

Link: http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php

2022-05-12 13:27 UTC, hmiranda99 requested changes
### Pontos vistos

## Reponsividade em telas pequenas
- Quando coloca a reponsividade no `galaxy fold` por exemplo, como é uma tela pequena e o título `adicionar informações` é grande, o ícone hamburguer desaparece. Acredito que na visão mobile, não precise da logo no header. Assim ele terá mais espaço para os títulos. Caso queira, pode colocar a logo dentro do menu, para ficar parecido com o menu da página web, fique a vontade! mas não é obrigatório.

### Alinhamento menu visão mobile
**(Risco vermelho na imagem)**
- Acho que se houver a probabilidade de os ítens do menu ficarem alinhados a parte esquerda do botão, irá ficar bem mais lindo. 

**(Risco amarelo na imagem)**
- E para melhorar ainda mais o alinhamento dos objetos, quando retirar a logo do header, poderia ter uma margin e os objetos ficarem rente a ela na parte esquerda.
![mobile](https://user-images.githubusercontent.com/79329906/168085589-49fd4e60-8e08-4ca1-be64-b13cdfa22b73.png)


*Ficou um arraso!* 👧🏼

2022-05-12 22:22 UTC, gustavodesantana approved these changes

2022-05-13 00:38 UTC, emillienicole approved these changes
Arrasoooooooou

2022-05-13 00:49 UTC, Gih08 approved these changes

2022-05-13 01:11 UTC, merged