feat/update-teacher
kvlsndkf/project pull request #17
Opened 2022-05-13 14:56 UTC by emillienicole

<strong><h3>Antes de clicar no link... para dar certo precisa-se:</h3></strong> 
- Cadastrar algum professor no card "Card cadastro";
- Clicar no link "Editar" abaixo da foto do professor, que é onde está a página estilizada.

<a href="http://localhost/project/private/adm/pages/register/register-teacher/list-teacher.page.php" class="link"> Clique aqui!</a>

<style> 
.link {
color: pink;
}
</style>

Estilização e verificação feita da página update-teacher, como não temos um modelo no protótipo, fiz uma cópia do "register-teacher", qualquer sugestão de alteração que seja viável (de layout, se tiver algum defeito/erro, fazer um RC), falar comigo no Whatsapp.

2022-05-14 14:38 UTC, Ti-Alves approved these changes
revisado e aprovado!

2022-05-14 21:47 UTC, hmiranda99 requested changes
Perfeito, só o hover o botão que está errado.

2022-05-15 13:37 UTC, hmiranda99 approved these changes

2022-05-15 13:37 UTC, MayaraPereira17 approved these changes

2022-05-15 13:39 UTC, gustavodesantana approved these changes

2022-05-15 13:44 UTC, merged