Listagem de Professores
kvlsndkf/project pull request #18
Opened 2022-05-15 17:02 UTC by Ti-Alves

Pull Request referente à página `list-teacher,page,php` para a listagem e a manipulação dos cadastros dos Professores.

Link: http://localhost/project/private/adm/pages/register/register-teacher/list-teacher.page.php

2022-05-15 17:32 UTC, emillienicole requested changes
Tem uma seta a mais no menu, e de acordo com o protótipo, não é necessária:
![image](https://user-images.githubusercontent.com/79720171/168486008-c03b12ed-4363-45f6-95ec-d5a8a7546122.png)

Só essa observação mesmo, sempre babo nessa responsividade maraaaa!

2022-05-15 23:26 UTC, emillienicole approved these changes

2022-05-16 11:44 UTC, hmiranda99 requested changes
Muito bom!

## Pontos vistos
### Animação na seta de voltar
**A animação na seta atrapalha o clique, vamos evitar usar tanta animação porque essas coisas deixam a página mais pesada.**

### Barra de pesquisa
**Ao clicar na barra de pesquisa, a borda deve ficar na mesma cor que ficam os inputs (azul)**

### Excluir
**Quando clica em `excluir` no card que aparece na listagem de busca, o modal para exclusão não aparece**

### Responsividade
**Quando estamos na visão mobile, o botão de pesquisar fica bem pequeno dificultando o clique**
![image](https://user-images.githubusercontent.com/79329906/168585359-e2e3b0b7-e697-488d-ba7f-ff76f3e58310.png)

2022-05-16 23:58 UTC, Palominha approved these changes

2022-05-17 00:48 UTC, Gih08 approved these changes

2022-05-17 00:58 UTC, garcia235 approved these changes

2022-05-17 11:46 UTC, hmiranda99 approved these changes
Perfeito!!!

2022-05-17 13:06 UTC, merged