Feat/delete teacher modal
kvlsndkf/project pull request #19
Opened 2022-05-15 17:22 UTC by emillienicole

Modal do aviso de exclusão do professor estilizado de acordo com o protótipo.

🔗 <a href="http://localhost/project/private/adm/pages/register/register-teacher/list-teacher.page.php">Clique aqui!</a>

2022-05-15 23:16 UTC, Ti-Alves approved these changes

2022-05-16 11:50 UTC, hmiranda99 requested changes
**Achei estranho, mas eu abri aqui e o modal está normal, até tirei print da página toda para ver que estou na URL que você indicou**

##

![image](https://user-images.githubusercontent.com/79329906/168586305-8c6b5cd6-c7ed-40aa-af21-fde065186083.png)

2022-05-16 20:41 UTC, gustavodesantana approved these changes

2022-05-16 23:32 UTC, Gih08 approved these changes

2022-05-17 00:08 UTC, Palominha approved these changes
Parabéns!!! Está muito lindoo!

2022-05-17 00:56 UTC, garcia235 approved these changes

2022-05-17 01:16 UTC, merged