CSS Global
kvlsndkf/project pull request #2
Opened 2022-04-13 03:32 UTC by Ti-Alves

Criada a pasta `styles` para acomodar o novo arquivo `style.global.css`, que tem as devidas variáveis de cor, peso, tamanho e fontes para a estilização do projeto.

2022-04-13 11:17 UTC, hmiranda99 requested changes
Parabéns pelo capricho e rapidez!

### Fontes baixadas:
- Está faltando algumas fontes, nós usamos três tipos diferentes no nosso projeto.
<img width="231" alt="Captura de Tela 2022-04-13 às 08 13 51" src="https://user-images.githubusercontent.com/79329906/163168712-7464b707-4243-4868-b0c6-e456d73ee474.png">

2022-04-13 11:27 UTC, hmiranda99 requested changes

2022-04-13 11:27 UTC, hmiranda99 commented on views/styles/style.global.css
> +    --violet: #B377F3;
Está faltando as cores gradientes, e os nomes das cores estão diferentes das do protótipo, isso aumenta o tempo de procura dos fronts nas cores certas.

2022-04-13 11:27 UTC, hmiranda99 commented on views/styles/style.global.css
> +    --h2: 48px;
Por hora, esses tamanhos não existem.

2022-04-13 11:27 UTC, hmiranda99 commented on views/styles/style.global.css
> +    --small: 12px;
Estão faltando tamanhos das fontes pequenas.

2022-04-13 11:27 UTC, hmiranda99 commented on views/styles/style.global.css
> +    --extra-bold: 800;
Ao invés de `extra-bold`, usamos o `black`.

2022-04-13 11:27 UTC, hmiranda99 commented on views/styles/style.global.css
> +
As fontes tem o `line heigth` definido, que é o tamanho da caixa da fonte. Então é mais uma variável a ser adicionada. E como os estilos de fontes, são bem específicos, caso você queira poderá já criar um `font.style.css`, nele terá as classes dos respectivos estilos já que você está mechendo nessa parte e conhece bem. Assim, facilitando quando começarmos a produção, mas caso não queira, crio a tarefa e passamos para outro fron, tá bom?

2022-04-13 14:16 UTC, Ti-Alves commented on views/styles/style.global.css
> +    --violet: #B377F3;
cores renomeadas e gradientes adicionados!

2022-04-13 14:17 UTC, Ti-Alves commented on views/styles/style.global.css
> +    --h2: 48px;
eu deixei eles pois no caso de uma nova tela ser criada com estes tamanhos padrões nós ja termos as variaveis porem ja foram retiradas!

2022-04-13 14:18 UTC, Ti-Alves commented on views/styles/style.global.css
> +    --extra-bold: 800;
variavel renomeada

2022-04-16 13:15 UTC, hmiranda99 approved these changes
Boooaaa 🎉

2022-04-16 13:15 UTC, Palominha approved these changes

2022-04-16 13:21 UTC, Gih08 approved these changes

2022-04-16 13:25 UTC, gustavodesantana approved these changes

2022-04-16 14:06 UTC, merged