ADM Dashboard
kvlsndkf/project pull request #23
Opened 2022-05-18 15:37 UTC by emillienicole

Estilização em progresso

2022-05-22 21:46 UTC, hmiranda99 requested changes
### Pontos vistos
A responsívidade está PERFEITAAAA NO MOBILE

### Tela média
A distância entre os cards estão muito grandes, tanto dos cards brancos, como dos coloridos. Seria bom que a distância deles fossem menor, igual no protótipo, porque se o dado que estiver vindo for muito grande tipo 100.000 alunos, pode não caber no card
![image](https://user-images.githubusercontent.com/79329906/169717202-19824317-b5c3-4c17-8404-4da00f9c8290.png)

### Tela bem grande
E em um monitor maior ele fica beeem afastado
![image](https://user-images.githubusercontent.com/79329906/169717239-4c8c52f8-1c3a-4b75-b0ea-b1faebb7c019.png)
![image](https://user-images.githubusercontent.com/79329906/169717289-8c51c63b-436b-4802-afb9-5331854d6126.png)

2022-05-23 23:19 UTC, Gih08 approved these changes

2022-05-24 02:07 UTC, Palominha reviewed
Observei os mesmos pontos que a Helena observou!

2022-05-25 00:55 UTC, Gih08 approved these changes

2022-05-25 14:31 UTC, Ti-Alves approved these changes
Revisada e aprovada!✨

2022-05-25 14:34 UTC, merged