Feat/courses back end
kvlsndkf/project pull request #25
Opened 2022-05-22 00:12 UTC by hmiranda99

2022-05-22 14:46 UTC, Palominha requested changes
Estava fazendo alguns cadastros que precisam existir para criar o curso, e noitei algumas coisas:
## Parte de cadastrar matéria 

*Quando clica em salvar (na parte de lote) sem selecionar nada, ele envia para um tela toda branca.
*O cadastro foi com apenas uma letra (mas acho que isso quem cuida também é o front).
*Quando eu edito, limpo o nome e aperto em cadastrar, ele cadastra sem nada no input (Ai, quando eu vou selecionar a matéria na tela do curso, ele aparece um espaço em branco).

![img](https://user-images.githubusercontent.com/79668109/169700376-1f04c1ad-ea63-4e64-8758-93de22360515.png)

##Sobre o Curso

*Na parte da materia, quando você atualiza o input sem nada, na hora de cadastrar esse espaço vazio no curso, ele vai tranquilo.
*Não deixa você cadastar sem nenhuma informação, porém quando eu aperto em editar e tiro o nome do curso e o sobre, ele salva sem nada nesses dois. (Ele também edita sem nada no sobre).

2022-05-22 18:23 UTC, emillienicole reviewed
Concordo com as observações da Paloma, de resto ta tudo certo! Parabénssss

2022-05-23 01:47 UTC, Gih08 approved these changes

2022-05-23 01:52 UTC, Palominha commented
> Revisado e Aprovadíssimo!!🌟 🎉

2022-05-23 01:53 UTC, Palominha reviewed
Revisado e aprovadíssimo!!! 🎉✨

2022-05-23 01:53 UTC, Palominha reviewed
Aprovado!!

2022-05-23 01:56 UTC, Ti-Alves approved these changes

2022-05-23 02:05 UTC, gustavodesantana approved these changes

2022-05-23 02:47 UTC, emillienicole approved these changes

2022-05-23 17:55 UTC, Palominha approved these changes

2022-05-23 17:57 UTC, merged