Feat/pagination-etecs
kvlsndkf/project pull request #27
Opened 2022-05-22 02:40 UTC by gustavodesantana

2022-05-23 01:26 UTC, hmiranda99 requested changes
## Pontos vistos
Não aparece o total de resultados do filtro, mostra por página.

2022-05-24 01:48 UTC, hmiranda99 approved these changes
Aprovado!

2022-05-24 01:51 UTC, emillienicole approved these changes
revisado e aprovado

2022-05-24 01:53 UTC, Gih08 approved these changes

2022-05-24 01:53 UTC, Palominha approved these changes

2022-05-24 02:57 UTC, merged