Listagem de Cursos
kvlsndkf/project pull request #31
Opened 2022-05-25 14:51 UTC by Ti-Alves

2022-05-26 14:12 UTC, emillienicole requested changes
<h1>Pontos vistos</h1>

- Responsividade
> Responsividade perfeita! Mas a responsividade dos cards é quebrada quando um nome do curso é muito grande (inclusive só testei isso agora, pode estar acontecendo com as outras telas de listagem que foram para QA já), segue os anexos:
<hr>
![image](https://user-images.githubusercontent.com/79720171/170504218-f0fc6785-038e-4172-b202-a46b528e8d94.png)
![image](https://user-images.githubusercontent.com/79720171/170504390-3dcf0ed6-fe4c-4747-8fe0-7f850c4e863e.png)

_Sugiro que veja a questão de texto truncado, tem o link do bootstrap para isso:_
https://getbootstrap.com/docs/5.1/helpers/text-truncation/

- Sidebar
> É prático que todo o botão de **"adicionar informações +"** seja clicável, não só nessa página mas em todas que ainda não foi mudado, foi uma observação da Helena na minha PR e sugiro que corrija também, qualquer coisa só consultar a sidebar do dashboard em QA
<hr>
![image](https://user-images.githubusercontent.com/79720171/170501960-0ef725f0-9a6c-4efd-95b3-bb216caf2b42.png)
<hr>

> **Hover Dashboard:** Foi implementado um novo hover para as páginas que estão estilizadas no sidebar, (apenas o dashboard) pode consultar na sidebar de adicionar informações em QA, segue um exemplo do protótipo
<hr>
![image](https://user-images.githubusercontent.com/79720171/170502948-3d6b47c3-10c1-46b3-bb64-f012bdfaf305.png)

2022-05-28 01:29 UTC, hmiranda99 requested changes
## Pontos vistos

### Link para o dashboard
> Não tem link indo para o dash

### Chip matérias
> O chips das matérias não está aparecendo.

## Todo o resto está muito lindo! Parabéns pela dedicação 🎉

2022-05-28 13:19 UTC, Palominha reviewed
Observado os mesmos pontos que a Helena!

2022-05-28 15:17 UTC, Palominha approved these changes
Revisado e Aprovado!!!!!!!! ✨

2022-05-28 17:08 UTC, hmiranda99 approved these changes
revisado e aprovado!! 🎉

2022-05-28 18:25 UTC, gustavodesantana approved these changes

2022-05-28 20:57 UTC, Gih08 approved these changes

2022-05-29 13:05 UTC, emillienicole reviewed
Tudo perfeitooooo, parabéns! Só senti falta do link para acesso ao dashboard na sidebar da listagem de cursos, já que a página já existe é melhor colocar o link agora ao invés de ter que colocar lá na frente

2022-05-29 13:08 UTC, emillienicole approved these changes
Arrasooooooooo

2022-05-29 13:10 UTC, merged