Cadastro do fale conosco: Email e Mensagem
kvlsndkf/project pull request #33
Opened 2022-05-26 22:45 UTC by garcia235

2022-05-27 14:07 UTC, hmiranda99 requested changes
## Pontos vistos

### Link na descrição do respositório
> O link está indo para uma página que não existe.

### Onde testar?
> Entrei na landing page do help e quando clica em `fale conosco` não aparece o modal. Entrei na página para ver o código e também não encontrei nenum código referente ao modal.

### Encontrei!
> A página está no local errado, ela deve seguir o cenário acima.

### Banco de dados
> O tamanho máximo do text área está incorreto, verifique o tamanho no banco. É indicado colocar um tamanho um pouco menor do que o máximo, porque caso estoure o tamanho o banco não vai emitir erros.
<br>

> O tipo do banco também deve ser alterado, o email deve ser `text` ao invés de `varchar`, e não precisa estipular um tamanho máximo no banco.

2022-05-28 00:22 UTC, gustavodesantana requested changes
## Pontos vistos

### Encontrei!
> No modal falta um botão de excluir 

> Falta divider entre os campos para separa-los

>Também falta um botão para sair

>Exemplo de divider e do botão de sair
![WhatsApp Image 2022-05-27 at 21 20 17](https://user-images.githubusercontent.com/79333823/170802444-41ece0c0-ca2b-49f8-9a7c-7fa5b6ed1142.jpeg)

### Banco de dados
> A tabela status no banco de dados não está recebendo nenhum atributo

![image](https://user-images.githubusercontent.com/79333823/170802335-4b712f07-4a76-40c5-b0e3-70b2f8d96f31.png)
<br>

2022-05-29 19:35 UTC, hmiranda99 approved these changes
Revisado e aprovado! 🎉 
Parabéns!

2022-05-29 19:36 UTC, Gih08 approved these changes

2022-05-29 20:21 UTC, emillienicole approved these changes
Revisado e aprovado!

2022-05-29 21:24 UTC, Ti-Alves approved these changes
revisado e aprovado

2022-05-29 22:52 UTC, gustavodesantana approved these changes

2022-05-29 22:54 UTC, merged