Modais das Matérias
kvlsndkf/project pull request #41
Opened 2022-05-30 00:21 UTC by Ti-Alves

ta vindo

2022-05-31 17:58 UTC, Palominha approved these changes

2022-05-31 18:21 UTC, hmiranda99 requested changes
## Cadastro unitário
- Não tem limite mínino no input

2022-06-01 01:12 UTC, emillienicole approved these changes
Arraso!!

2022-06-01 14:48 UTC, hmiranda99 requested changes
## Estamos quase no fim!

#### Ponto visto
![image](https://user-images.githubusercontent.com/79329906/171432967-8d22374a-b1d0-444a-83fd-d79e1b756208.png)

As setinhas de voltar, tanto no cadastro de update, quanto no de cadastro mesmo kkk estão dessa forma.

#### Modal de excluir
- a frase está assim *A matéria também será excluída de seus cursos e módulos vinculados* 
- a matéria não tem módulo vinculado, então não precisa falar deles tá bom?

2022-06-01 15:06 UTC, hmiranda99 approved these changes
IIRRRUUUUUUULLLLLL

2022-06-01 23:36 UTC, Gih08 approved these changes

2022-06-01 23:48 UTC, merged