Feat/linkagem pages
kvlsndkf/project pull request #42
Opened 2022-05-30 13:05 UTC by MayaraPereira17

http://localhost/project/views/landing-page/landing-page.php#

http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php

-coloquei os links do mdBoostrap
-linkagem da navegação entre as paginas, desde da cold wold

2022-05-30 14:12 UTC, emillienicole requested changes
> - **Sidebar**

> Senti falta do link na sidebar para ir para o Dashboard nas seguintes páginas:
- Professores;
- Módulos;
- Etec's.

> - **Seta de voltar**
> Como eu fiz algumas telas de cadastro antes da mudança de tirar a página independente `search` , tem erro na volta da seguinte página:
- Cadastro professor

2022-05-30 23:59 UTC, hmiranda99 requested changes
### Pontos vistos
1. Somente a página de cursos que tem o link para o dashboard.

2022-05-31 02:36 UTC, Palominha requested changes
## Pontos vistos:

*Eu entro na tela de "O que você é?", clico no perfil de aluno, e volto para "O que é você", a seta que deveria me levar para o login, me leva novamete para as etapas do login.

2022-05-31 20:10 UTC, hmiranda99 requested changes
## Pontos vistos
- Quando você segue o seguinte caminho login> tipo de cadastro>etapa 1 cadastro aluno>e tenta voltar para o `tipo de cadastro` ele retorna para `etapa 1 cadastro aluno`.
-

2022-06-03 21:53 UTC, emillienicole requested changes
<h1>Pontos vistos</h1>

<h3><a href="http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php">Página "Adicionar Informações"</a></h3>

- **Todo o corpo da página de Adicionar Informações sumiu, deve ter mexido em alguma coisa a mais quando resolveu conflitos, só um chute mesmo, dá uma olhada no que rolou**
- **O botão do sidebar "Sair" sumiu**
- **Uma característica diferente que notei foi que no sidebar, o scroll está infinito, mesmo depois do conteúdo ter acabado, e nas outras páginas não**
![image](https://user-images.githubusercontent.com/79720171/171952489-668b36cb-b774-4446-9544-f23f25001b41.png)
<hr>

<h3><a href="http://localhost/project/private/adm/pages/register/register-course/list-course.page.php">Página "Listagem de Cursos"</a>, <a href="http://localhost/project/private/adm/pages/register/register-subject/list-subject.page.php">Página "Listagem de matérias"</a>, <a href="">Página "Listagem de módulos"</a><h3><a href="http://localhost/project/private/adm/pages/register/register-teacher/">Página "Listagem de professores"</a></h3>

-  List course: Na `linha 164` e `linha 168` tem textos avulsos que apareceram no sidebar, retire-os;
- List module: Mesmo problema citados acima, na `linha 153` e `linha 157`;
- List subject: Mesma coisa, `linha 163` e `linha167`;
- List teacher: Mesma situação `linha 153` e `linha 157`
<hr>
<h3><a href="http://localhost/project/private/adm/pages/register/register-school/list-school.page.php?filterSchool=">Página "Listagem de ETECs"</a></h3>

- Os filtros ficam gigantes por meio segundo ao clicar neles
<hr>
<h3><a href="http://localhost/project/private/adm/pages/register/register-teacher/form-register-teacher.page.php">Página "Cadastrar professor"</a></h3>

- Como já foi pedido, precisa mudar o caminho da seta de voltar do formulário, porque a página `search-teacher` não existe mais, ela deve voltar para a listagem de professores.

2022-06-05 02:58 UTC, closed without merging