Tela de escolha de perfil (Aluno ou Empresa)
kvlsndkf/project pull request #5
Opened 2022-04-20 20:16 UTC by emillienicole

🔗 **LINK DE ACESSO**
http://localhost/project/views/pages/register/register-profile/register-profile.pages.php

🗃 **ARQUIVOS MEXIDOS** 
> **Pages**
Fiz uma pasta geral para colocarmos todas as telas de cadastro de usuário, chamada _register_ e lá dentro criei a pasta _register-profile_ (a que eu mexi) e _register-student_ onde futuramente estará a tela que tem um form para cadastro do aluno, de acordo com nosso protótipo.

> **Images**
Lá coloquei as imagens necessárias em sua devida pasta, assim conseguimos ter um melhor controle de onde fica o que, seria bom se assim se mantivesse. Todas imagens necessárias para minha tarefa estão lá, como os avatares. Caso tenha dúvida de qual avatar é qual, usei o mesmo nome que está nos grupos do protótipo.

![profile](https://user-images.githubusercontent.com/79720171/164315137-cbbbdd24-6bef-40c3-88a4-1d4ccd2fde02.png)

2022-04-20 20:19 UTC, MayaraPereira17 approved these changes
Parabenasssssss

2022-04-20 20:56 UTC, hmiranda99 requested changes
Na minha tela ficou assim:
![nicole](https://user-images.githubusercontent.com/79329906/164321284-ede4c6cf-5918-4f15-b649-6f2da9e976eb.png)

2022-04-21 02:50 UTC, emillienicole commented
> Na minha tela ficou assim: ![nicole](https://user-images.githubusercontent.com/79329906/164321284-ede4c6cf-5918-4f15-b649-6f2da9e976eb.png)

Arrumado no novo commit, obrigada! Por favor, verifica se ainda está :)

2022-04-21 16:13 UTC, hmiranda99 approved these changes
obaaaaaaaaa :tada:

2022-04-21 16:13 UTC, Ti-Alves approved these changes

2022-04-21 16:14 UTC, gustavodesantana approved these changes

2022-04-21 16:14 UTC, Gih08 approved these changes

2022-04-21 17:03 UTC, merged