feat/style-in-progress
kvlsndkf/project pull request #52
Opened 2022-06-01 02:55 UTC by emillienicole

Loading...

2022-06-04 02:41 UTC, Palominha requested changes
## Pontos Observados:

* Ele permitiu eu cadastrar números.
![image](https://user-images.githubusercontent.com/79668109/171975337-fa9cfa83-5cdd-4b81-af8e-44e30675f1f7.png)

2022-06-05 02:48 UTC, Gih08 approved these changes

2022-06-05 03:18 UTC, hmiranda99 requested changes
### Pontos vistos

### Layout
- Senti falta de uma margin entre o form no topo e no fim da página.

### Validação
- Eu tinha escrito menos do que 100, só que depois eu escrevi à mais e ele ainda persistia dizendo que eu não tinha escrito os 100.
![image](https://user-images.githubusercontent.com/79329906/172033489-1d582af7-852c-4f6e-9d30-e4ab7420c659.png)

2022-06-06 14:36 UTC, hmiranda99 approved these changes
Revisado e aprovadasso!

2022-06-06 18:23 UTC, gustavodesantana approved these changes

2022-06-06 22:12 UTC, garcia235 approved these changes

2022-06-07 00:03 UTC, Palominha approved these changes

2022-06-07 01:14 UTC, merged