Feat/list message
kvlsndkf/project pull request #55
Opened 2022-06-03 23:45 UTC by Gih08

2022-06-04 23:49 UTC, emillienicole approved these changes
Me parece tudo certinho! Parabéns às envolvidas

2022-06-05 00:48 UTC, Ti-Alves approved these changes
Revisado e aprovado!

2022-06-05 03:27 UTC, hmiranda99 requested changes
### Pontos vistos

#### Link landing page
- O link fornecido está incorreto.

#### Contador de mensagens lidas
- Quando não tem mensagens lidas o contador fica em 1
![image](https://user-images.githubusercontent.com/79329906/172033713-dcb268af-1db6-473a-83fe-26aa9f222864.png)

2022-06-05 18:20 UTC, hmiranda99 approved these changes
tudo ok

2022-06-06 01:49 UTC, Palominha approved these changes

2022-06-06 10:57 UTC, merged