Fix/Hover no Botão de sair
kvlsndkf/project pull request #56
Opened 2022-06-04 01:45 UTC by Palominha

## O que foi feito:
* Hover colocado com sucesso no Botão de sair!!!! 

###Link 
http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php

2022-06-04 18:39 UTC, Gih08 approved these changes

2022-06-04 23:51 UTC, emillienicole approved these changes
Lindissimoo

2022-06-05 00:44 UTC, Ti-Alves approved these changes
Revisado e aprovado

2022-06-05 03:32 UTC, hmiranda99 requested changes
### Pontos vistos

### Falta de link do dashboard
- Adicionar informações
- Professores
- Módulos
- Etecs

### Página sem o hover
- Professores
- Módulos
- Matérias
- Dashboard
- Etecs
- Cursos

2022-06-06 12:27 UTC, hmiranda99 approved these changes

2022-06-06 12:27 UTC, merged