Modal Sobre dos Cursos
kvlsndkf/project pull request #59
Opened 2022-06-05 17:36 UTC by Ti-Alves

ta vindo

2022-06-06 12:35 UTC, hmiranda99 requested changes
### Pontos vistos

#### Etec
- A etec não tem foto e está faltando o local.
![image](https://user-images.githubusercontent.com/79329906/172161418-ffc5e795-6e79-4154-928f-7eab87e553c8.png)

#### Matérias
- A distância da parte de cima está muito grande, deve ser a mesma distância dos professores.
![image](https://user-images.githubusercontent.com/79329906/172161525-9b3b2972-682d-46a8-b523-88e5374273dd.png)


#### Paginação
- Como está:
![image](https://user-images.githubusercontent.com/79329906/172161129-485be973-53cc-472e-a723-1050610af2ba.png)

#### As letras estão escuras

- Como deve ser:
![image](https://user-images.githubusercontent.com/79329906/172161167-f9a6292f-7e77-45af-9ee9-c0b6a1d854c7.png)

2022-06-08 15:15 UTC, hmiranda99 requested changes
### Pontos vistos

### Etec
- Na lista de etec, faltou o divider entre elas

### Professores
- A foto está perfeita! Mas tem uma `margin-top`  muito pequena entre ela e o divider, está desigual com a parte de baixo.

2022-06-08 19:03 UTC, MayaraPereira17 approved these changes

2022-06-09 01:38 UTC, Gih08 approved these changes

2022-06-12 13:31 UTC, hmiranda99 approved these changes

2022-06-12 13:31 UTC, merged