Landing Page Heelp!
kvlsndkf/project pull request #6
Opened 2022-04-22 22:52 UTC by Ti-Alves

##Link de Acesso:
http://localhost/project/views/landing-page/landing-page.php

O que foi feito: criada a pasta `/landing-page` para acomodar o `landing-page.php`, e seu arquivo de estilização e foram adicionadas algumas fotos .svg para uso na landing page.

2022-04-23 19:26 UTC, hmiranda99 requested changes
É tão bom ver o projeto saindo do protótipo e chegando na nossa telinha! 😄 

## Pontos vistos
- ### Menu:
- **Alinhamento das labels:** Senti falta das labels alinhadas com a logo e os botões.
![image](https://user-images.githubusercontent.com/79329906/164943063-53fc2ab1-1845-4436-ad11-904b5f806ee2.png)

- **Hover:** O hover ainda está bem escuro, praticamente não dá para enchergar o que está escrito.
![image](https://user-images.githubusercontent.com/79329906/164943087-2b748a92-2ceb-4d2c-bdb7-22e9d889c179.png)

- **Alinhamento com o container:** Senti falta do alinhamento do menu com o container.
![image](https://user-images.githubusercontent.com/79329906/164943205-351811df-4c29-4833-a63f-46357fdf7ef8.png)

- **Cor da logo**: A cor dos olhinhos da logo não estão da cor primária.
**Sugestão:** Salvar a logo sem cor nos olhinhos e na boca, assim ela fica trasnparente e se adequa ao background em que estiver.
![image](https://user-images.githubusercontent.com/79329906/164943239-a4cd946a-c223-4111-8401-29cf9884cbd1.png)



### Footer
- **Botão âncora**: O botão poderia ficar alinhado ao container do página, igual ao protótipo.
**Página:**
![image](https://user-images.githubusercontent.com/79329906/164943158-0c7cdc5c-0921-420a-8a81-704f992ec788.png)
**Protótipo:**
![image](https://user-images.githubusercontent.com/79329906/164943178-bd666e31-ab8c-4684-9d4f-53c3bb683e2b.png)

### Responsividade:
- **Imagens**: As imagens não estão se enquadrando a tela, segue os prints:
![image](https://user-images.githubusercontent.com/79329906/164943334-1c315b64-b8ed-4645-bd1f-beb5fd8ef38a.png)

**Aqui está sem imagens e sem a margem da tela e com isso está cortando os parágrafos**
![image](https://user-images.githubusercontent.com/79329906/164943342-8b2d2e8e-5589-40ea-8508-4e62377dbdb7.png)
![image](https://user-images.githubusercontent.com/79329906/164943354-38c69171-748a-4afc-92f3-070fd0233d8b.png)

**No fim da página estamos com as mesmas questões do começo e sem o botãozinho âncora**
![image](https://user-images.githubusercontent.com/79329906/164943390-58c1dc0c-c666-49be-81df-04604bdd1126.png)

2022-04-25 12:50 UTC, emillienicole requested changes
Notei alguns pontos enquanto fazia testes de responsividade, além dos detalhes levantados pela Helena, na largura da tela que estarei mostrando na imagem abaixo, alguns elementos ficam quebrados e vão para outros containers:
![responsividade](https://user-images.githubusercontent.com/79720171/165090378-9fbe4787-bc66-4d22-aaaf-e20b797727dc.png)
![image](https://user-images.githubusercontent.com/79720171/165090863-ce13f75d-0ce1-4884-b6d7-c95e09df7501.png)

E sobre o hover do footer, mesma opinião da Helena em relação a cor escura, poderia ser um fade mais suave, com uma cor mais clara.

Agora uma pergunta sobre o JS da navbar, notei que está começando o scroll apenas a partir da section 2 da página (if scroll > 500), o que na minha opinião poderia começar antes para não acontecer esses problemas de sobreposição com o texto:

![image](https://user-images.githubusercontent.com/79720171/165092492-3b9b4bc4-a62c-4fc9-a1c0-650dfc68ede0.png)

![image](https://user-images.githubusercontent.com/79720171/165092771-2fc4f174-7c15-4e63-9275-4090586167bc.png)

2022-04-30 03:24 UTC, MayaraPereira17 reviewed
na parte (É pedindo e dando Heelp! que você se destaca)
a imagem quando deixa ela  para celular nao esta centralizada esta mt para a esquerda

2022-05-08 07:05 UTC, MayaraPereira17 approved these changes

2022-05-09 13:35 UTC, emillienicole approved these changes
Aaaaaaaaaaai a coisa mais linda, não vi nenhum ajuste a ser feito, **ARRASOU!**

2022-05-09 23:19 UTC, hmiranda99 approved these changes

2022-05-10 17:09 UTC, garcia235 approved these changes

2022-05-10 17:10 UTC, merged