Página do Fale Conosco
kvlsndkf/project pull request #64
Opened 2022-06-07 20:01 UTC by Ti-Alves

ta vindo

2022-06-08 14:09 UTC, emillienicole requested changes
Muito lindooo! Só umas pequenas observações:

- Colocar o mesmo hover que está dentro da página de Fale conosco nas outras que tem o mesmo sidebar (apenas no item fale conosco);
- O link da setinha de voltar da  página de fale conosco não está voltando, o link está errado.

2022-06-08 15:23 UTC, hmiranda99 requested changes
### Pontos vistos

### Card
- Com uma mensagem grande, além de ela não ocupar 100% do `width` do card, ela não está truncada.
- A distância entre os cards está muito grande.
- Isso também ocorre nas mensagens lidas.
![image](https://user-images.githubusercontent.com/79329906/172654478-62c36544-a4df-4935-aa1d-c60b7b983800.png)

### Página
- O `padding-top` da barra de pesquisa e o top está muito grande.
- A distância pode ser a mesma que a do `padding-bottom`
![image](https://user-images.githubusercontent.com/79329906/172654942-97904c39-aaec-4299-a9a3-65897279813e.png)

2022-06-08 19:06 UTC, MayaraPereira17 approved these changes

2022-06-08 22:56 UTC, emillienicole reviewed
Notei agora que não tem cursor pointer na página Fale Conosco no botão de adicionar infos

No dashboard não tem o hover padrão das outras no item Fale Conosco

2022-06-09 23:57 UTC, emillienicole approved these changes
irrulll

2022-06-10 15:54 UTC, garcia235 approved these changes

2022-06-11 15:04 UTC, Gih08 approved these changes

2022-06-13 02:21 UTC, hmiranda99 approved these changes

2022-06-13 02:23 UTC, merged