Fix/estilo modal fale conosco
kvlsndkf/project pull request #65
Opened 2022-06-09 04:19 UTC by Palominha

## O que foi feito:

* Foi estilizado o modal Fale Conosco.
***Infelizmente eu não consegui inserir a imagem botinho, por isso peço desculpas...***

* Ele já está funcionando igual ao anterior, mas antes testem de tudo, desde a responsividade até se a mensagem chega no lugar certo.

### Link 

http://localhost/project/views/landing-page/landing-page.php#

2022-06-10 01:22 UTC, emillienicole requested changes
Alguns detalhes a serem vistos

- Já foi feito um textarea na sessão de cadastro de ETECs por exemplo, poderia pegar ele como base, já que está bem próximo ao protótipo, coisas como ele não expandir, o contador, fonte, padding e etc já tem um padrão feito em código, o que torna mais fácil
> Se quiser entrar em call eu consigo ajudar!

- Eu entrei em QA e notei a diferença que por algum motivo, na sua branch o navbar da landing page quebrou um pouco a formatação

Sua branch:
![image](https://user-images.githubusercontent.com/79720171/172971189-82ed22a1-bb2a-45c5-bc7b-1ca83b9213e5.png)
QA:
![image](https://user-images.githubusercontent.com/79720171/172971260-01369f21-1da7-4985-93c9-9ea782e7b235.png)

- A responsividade da página quebra quando usamos o modal no celular
![image](https://user-images.githubusercontent.com/79720171/172971418-faed965d-6a9f-4737-915e-b606118a4bdb.png)

2022-06-10 14:30 UTC, hmiranda99 requested changes
- o erro ainda persiste
![image](https://user-images.githubusercontent.com/79329906/173087803-b9c2ba65-156f-4990-823e-8fb33ab55337.png)

> observação: esse assunto se refere a outra task, deveria ser implementado depois da conclusão da task do modal, agora temos dois assuntos misturados na mesma branch.

2022-06-12 13:35 UTC, hmiranda99 requested changes
## Ponto visto
- Não tem quantidade de caracteres mínimos

2022-06-12 16:41 UTC, hmiranda99 approved these changes

2022-06-12 17:54 UTC, Ti-Alves approved these changes

2022-06-12 18:14 UTC, emillienicole approved these changes
êeee

2022-06-12 18:16 UTC, merged