Estilo do Feed
kvlsndkf/project pull request #69
Opened 2022-06-14 04:03 UTC by Ti-Alves

ta vindo

2022-06-15 17:28 UTC, hmiranda99 requested changes
> Essa task tá me trazendo tanta felicidade! 😸 😍 

## Pontos vistos
### Card fazer pegunta
- Ele não está ocupando o width todo, não sei se ai também ficou assim.
![image](https://user-images.githubusercontent.com/79329906/173935545-b8bafed9-a239-4599-abca-a8d77cd50e16.png)

### Fazer pegunta mobile
- O botão de fazer pergunta é rosa, e ele pode ficar um pouquinho maior e mais distante do menu e da lateral direita.
- O menu poderia ter também mais paddin top e bottom, tipo o do twitter.
![image](https://user-images.githubusercontent.com/79329906/173938492-5ecc3809-4e73-4e69-b1ca-c006cf87e5a6.png)


- O `+` está azul, não sei se aí está assim, mas seria bom ele ser branco e em bold, para ficar em mais evidência. 
![image](https://user-images.githubusercontent.com/79329906/173938061-2f3cdd62-a95a-48ff-ba9e-9af73c2b1670.png)

2022-06-15 23:31 UTC, emillienicole reviewed
<h1>Tá ficando tãaaaaao lindo</h1>

> Como minha review está vindo depois da RC da Helena e os commits recentes, vi algumas coisas

- O cursor pointer no **módulo** e **etec** faz parecer que é clicável (minha percepção)
![image](https://user-images.githubusercontent.com/79720171/173955625-1a2f07e6-1023-41bb-8cea-026d0b05eb40.png)

- O `+` do ícone para fazer uma pergunta no celular continua azul
![image](https://user-images.githubusercontent.com/79720171/173957656-7b4e8e04-4012-42b9-9b09-36a5cad0701c.png)

- O card não está ocupando 100% no container principal

**Sua branch:**
![image](https://user-images.githubusercontent.com/79720171/173958172-2472fb37-f565-4d26-a85f-8a5e2cfe61b8.png)

**Protótipo:**
![image](https://user-images.githubusercontent.com/79720171/173958546-33b80703-1194-46d8-9cb3-95d79b9edc20.png)

2022-06-16 03:36 UTC, hmiranda99 requested changes
### Ponto visto

## Foto perfil
- Coloquei uma foto retângular (sem querer) e ficou assim kkkkk
![image](https://user-images.githubusercontent.com/79329906/173984806-5e3e1f79-843f-42a5-9d60-7c996e5b915c.png)

### Botão editar
- O botão poderia acompanhar a margem, para facilitar o toque. Se fosse no meu celular eu não conseguiria apertar, esse local não pega nele.
![image](https://user-images.githubusercontent.com/79329906/173985379-81b81f2b-8605-44ae-9c94-a0fdee362335.png)


### Imagens do post
- Algumas imagens estão passando da tela em alguns tamanhos de celulares, inclusive no safado do galaxy fold
- iphone SE
![image](https://user-images.githubusercontent.com/79329906/173985536-f484ca49-e4c6-4ef6-9789-98d57aeaac0c.png)

- samsung 
![image](https://user-images.githubusercontent.com/79329906/173985606-bbdcce8a-47e1-4f88-8abf-1ace4ad45131.png)

2022-06-16 14:14 UTC, emillienicole reviewed
Complementando a RC da @hmiranda99 a foto retangular horizontalmente fica assim também
![image](https://user-images.githubusercontent.com/79720171/174090127-ce158c6a-0194-44a1-be75-8c14980d1eac.png)

![image](https://user-images.githubusercontent.com/79720171/174089722-805c5100-02ee-4ef7-9b06-11f364d66233.png)
Além da foto da pergunta quebrar a responsividade no fold

2022-06-16 17:27 UTC, hmiranda99 requested changes
## Últimos pintos vistos, juro!
- A cor do "ver mais" deve ser azul, igual será no "ver mais" da paginação.
![image](https://user-images.githubusercontent.com/79329906/174130516-e1387854-42d6-49d8-8df3-0e0a5b65f0aa.png)

- Só o primeiro arquivo ficou com o botão do download torto, acredito que seja por causa do nome do arquivo que também é maior que os outros, poderia deixar ele truncado, que evitará a quebra se o nome foi muito gigante
![image](https://user-images.githubusercontent.com/79329906/174130935-c02ad74a-3fd9-438d-9244-efee3b80c24f.png)

2022-06-16 17:53 UTC, hmiranda99 approved these changes
P-E-R-F-E-I-T-O 🎉

2022-06-16 18:00 UTC, emillienicole approved these changes
Irrullllll

2022-06-16 18:21 UTC, Gih08 approved these changes

2022-06-16 18:26 UTC, garcia235 approved these changes

2022-06-16 18:37 UTC, merged