Estilização da página de pergunta
kvlsndkf/project pull request #74
Opened 2022-06-16 18:57 UTC by emillienicole

<h1>Estilização da página de pergunta</h1>

O que foi feito

- Estilização a partir do protótipo

> OBS.: A toolbar que formata o texto é junta ao textarea por JS padrão e não foi possível colocar abaixo dele, como no protótipo. O tamanho da textarea também é padrão e se adequa ao tamanho do texto.

<h1>Só acessa o link quem não é um robô:</h1>
<a href="http://localhost/project/private/student/pages/question/question.page.php">

![robo](https://user-images.githubusercontent.com/79720171/174144831-4af14a03-afa9-4b7e-961a-dd3cf6584b37.png)

</a>

2022-06-16 22:07 UTC, Ti-Alves approved these changes
revisada e aprovada!

2022-06-16 23:23 UTC, Gih08 approved these changes

2022-06-17 00:28 UTC, gustavodesantana approved these changes

2022-06-17 01:20 UTC, hmiranda99 requested changes
## Ponto visto
- Não sei como o placeholder do text area foi colocado, mas ele está constando como um texto e por isso está dando para fazer pergunta vazia

2022-06-17 01:44 UTC, merged