Feat/page/login
kvlsndkf/project pull request #8
Opened 2022-04-23 20:01 UTC by Palominha

Além da tela de login, na pasta style, eu adicionei um estilo chamado "additional.styles".
No grupo, vou mandar um áudio falando mais detalhes sobre ele.

2022-04-24 00:17 UTC, hmiranda99 requested changes
## Pontos vistos
A tela está diferente do protótipo

- **Tela atual:**
![image](https://user-images.githubusercontent.com/79329906/164950335-8251c3f8-a6ea-4b00-96a3-2868e3ce2bdf.png)

- **Protótipo:**
![página de login](https://user-images.githubusercontent.com/79329906/164950365-4ad056f2-116d-4b28-852d-251f6bc2487c.jpg)

2022-04-24 01:09 UTC, MayaraPereira17 approved these changes

2022-04-24 01:10 UTC, MayaraPereira17 approved these changes

2022-04-25 13:06 UTC, emillienicole requested changes
Para telas pequenas como a minha, houve scroll e seria legal se ele estivesse estilizado (como o scroll da landing page e do register-profile, segue o código css para aplicar se estiver de acordo:

`/* BARRA DE ROLAGEM */

::-webkit-scrollbar {
    width: 15px;
}

  ::-webkit-scrollbar-track {
    background: #40444B;
}

  ::-webkit-scrollbar-thumb {
    background: #bfbfff;
    border-radius: 5px;
    
}

  ::-webkit-scrollbar-thumb:hover {
    background: #8080FF;
}`

O hover do botão como já foi dito na reunião, pode ser alterado pensando no conceito de se colocar nesse, vai estar em todos, e precisamos escolher um que combine com outras cores e encaixe nos layouts
![image](https://user-images.githubusercontent.com/79720171/165094824-609f8fcb-9d6f-4b62-8d53-e9e4324d19a2.png)

2022-05-04 01:23 UTC, MayaraPereira17 approved these changes

2022-05-04 12:16 UTC, hmiranda99 requested changes
Tá ficando muito lindo! :tada:

### Pontos vistos
**Layout**
- Faltou o estilo do input clicado;
- A setinha de voltar está no local errado.
Como está:
![image](https://user-images.githubusercontent.com/79329906/166679111-8a329f8d-ba74-4573-9293-781c5993470e.png)

Como deve ser:
![image](https://user-images.githubusercontent.com/79329906/166679054-4cd65a4e-d324-4e01-8591-5b678ec9bb8a.png)

##

**Responsividade:**
- O conteúdo da página está saindo da tela.
![image](https://user-images.githubusercontent.com/79329906/166679272-9ce3e106-04e0-4718-9cc9-450dda2f72b2.png)

2022-05-14 22:01 UTC, hmiranda99 approved these changes
Revisada e aprovada! 🥇

2022-05-14 22:03 UTC, Ti-Alves approved these changes

2022-05-14 22:06 UTC, gustavodesantana approved these changes

2022-05-15 13:26 UTC, emillienicole approved these changes

2022-05-15 13:26 UTC, MayaraPereira17 approved these changes

2022-05-15 13:35 UTC, merged