Estilização da resposta
kvlsndkf/project pull request #80
Opened 2022-06-19 02:02 UTC by emillienicole

<h1>Estilização da página de responder perguntas</h1>

- De acordo com o protótipo a altura dos cards de resposta e pergunta estão ligados, então assim que colocar uma imagem, o outro card vai aumentar também;

- Para ver a página precisa ter uma pergunta para responder, clicando em **"Dar um help"** e assim que entrar nos detalhes da pergunta, clicar em **"Dar um help" novamente.**

> OBS.: Dei uma demorada porque algumas coisas do bootstrap estavam conflitando com a responsividade, então precisei fazer na mão com `@media`

<h1>Entre em Nárnia e veja a maravilha do front-end</h1>
<a href="http://localhost/project/private/student/pages/home/home.page.php">

![armario](https://user-images.githubusercontent.com/79720171/174462716-fa176eb4-09ab-48f9-af75-e32365bccdd9.png)

</a>

2022-06-19 02:32 UTC, hmiranda99 requested changes
### Pontos vistos

## Formatação selecionada
- Ao escolher uma formatação, o botão não fica mais azul
- Isso também está acontecendo na página de pedir o help, mas só consegui perceber agora. Descurpa.
*Como era*
![image](https://user-images.githubusercontent.com/79329906/174463298-210df62a-7664-492a-92b3-5b96899fce60.png)

*Como está*
![image](https://user-images.githubusercontent.com/79329906/174463321-fef02c71-7f3f-4cae-94dc-6df1f81dc840.png)

## Dividers
- Os dividers estão muito escuros, tente colocar a mesma cor que está na home.

## Botão dar help
- O botão está sem hover

##
Responsívidade perfeita!
Ficou mara o tamanho dos cards aumentando!!

2022-06-19 20:51 UTC, garcia235 approved these changes

2022-06-19 21:52 UTC, hmiranda99 approved these changes

2022-06-19 22:01 UTC, gustavodesantana approved these changes

2022-06-20 01:57 UTC, Gih08 approved these changes

2022-06-20 02:11 UTC, Palominha approved these changes

2022-06-20 02:37 UTC, merged