Estilização do Perfil do Aluno
kvlsndkf/project pull request #84
Opened 2022-06-19 15:16 UTC by Ti-Alves

...

2022-06-19 22:09 UTC, hmiranda99 requested changes
## Pontos vistos

### Pergunta
- Não sei se o link para pergunta está truncado, mas parece que não. Quando a pergunta é pequena aparece três pontinhos no fim da linha e quando a pergunta é grande, quebra o layout.
![image](https://user-images.githubusercontent.com/79329906/174502065-1629eec9-7def-4a6b-a260-1d30e96bda3c.png)

### Tabs
- Em todas as páginas tem tipo um título antes da pergunta, resposta ou material. esse título pode ser removido, assim vai ocupar um espaço menor.
![Captura de tela 2022-06-19 190534](https://user-images.githubusercontent.com/79329906/174502113-cf16f6b5-7add-4061-ae60-2d6766cd1bb8.png)

### Preferências
- As preferências não tem um divider

*Como está*
![image](https://user-images.githubusercontent.com/79329906/174502123-ebdb3bfc-6714-48a1-8526-1ab7e1153b59.png)

*Como é*
![image](https://user-images.githubusercontent.com/79329906/174502140-a19fa3c9-7302-4f2e-96ad-cca8c7da379c.png)

### Perfil lateral
- Quando eu entro no perfil de outra pessoa, some a minha foto e aparece a dela no perfil da navbar esquerda, acredito que tenha trocado as variáveis, porque eu dei uma testada em QA e tá tudo certo

*meu feed*
![image](https://user-images.githubusercontent.com/79329906/174502294-77bf3df7-a4e6-4a87-bc5c-addc5a566be7.png)

*quando entro no de alguém*
![image](https://user-images.githubusercontent.com/79329906/174502285-85e4967c-e660-4768-966e-42b01afd4729.png)

2022-06-19 22:37 UTC, hmiranda99 approved these changes

2022-06-20 01:44 UTC, Gih08 approved these changes

2022-06-20 01:49 UTC, gustavodesantana approved these changes

2022-06-20 02:21 UTC, Palominha approved these changes

2022-06-20 02:36 UTC, merged