feat/start
kvlsndkf/project pull request #86
Opened 2022-06-19 21:14 UTC by emillienicole

http://localhost/project/private/student/pages/search/search.page.php?search=a

2022-06-20 20:18 UTC, Palominha reviewed
## Pontos vistos:

* Faltou um padding-top ou margin-top na barra de pesquisa na responsividade
* Dar um outline none na barra de pesquisa e colocar um border.
* Estilizar a mensagem de que não teve resultados na pesquisa.

2022-06-21 02:53 UTC, Palominha approved these changes
Perfeito!!

2022-06-21 14:42 UTC, hmiranda99 requested changes
## Pontos vistos

### Tabs
- As tabs estão fora do padrão tanto em fonte, tamanho da fonte e o hover. Tente seguir o estilo que está no perfil do usuário.

*Como está*
![image](https://user-images.githubusercontent.com/79329906/174826293-1d17eb7b-3cc3-429f-8442-868fd50eb2f6.png)

*No perfil do usuário*
![image](https://user-images.githubusercontent.com/79329906/174826354-78f1ca18-19ec-4e64-aa87-f5ae3cf63136.png)

##
### Espaçamento das questões
- Está sem os espaçamentos, tente seguir o exemplo do perfil do usuário também
- O botão "ver" parece estar com a fonte diferente também

*Como está*
![image](https://user-images.githubusercontent.com/79329906/174826443-1901917b-fb2d-44c7-a0a7-1bc715c2c393.png)

*No perfil do aluno*
![image](https://user-images.githubusercontent.com/79329906/174826569-00812380-acbb-4856-bcc7-037d1205123d.png)

##
### Perfil
- O espaçamento também
- A linha abaixo do nome deve ser uma só

*Como está*
![image](https://user-images.githubusercontent.com/79329906/174826968-3516de42-c7a9-423b-be37-62ea567fedd1.png)

*Com base no perfil da etec do protótipo*
![image](https://user-images.githubusercontent.com/79329906/174829193-7157130d-02b4-4d63-b39b-644850929a8c.png)


##
### Sem respostas
- Deve ser centralizado
- A tag `strong` foi deixada e ai a palavra ficou difícil de ler pq a forma nativa já é `bold`, ai ficou bold em cima de bold. Seria bom deixar a frase com um cinza mais escuro e a palavra sem o `strong` só que na cor clara.

![image](https://user-images.githubusercontent.com/79329906/174827271-7f4d15f0-d036-4b39-9036-e4e4f5707c2b.png)

- Algumas partes estão com esse "dica", colocar em todas as mensagens
![image](https://user-images.githubusercontent.com/79329906/174828229-1e64d271-a48c-4d41-a9fe-e38d53bc0689.png)

- A idéia era que ficasse assim
![thread-38012329-17281291640438369755](https://user-images.githubusercontent.com/79329906/174828290-286bcce9-1006-4d17-89c6-3bab4b82edb6.jpg)

2022-06-22 02:30 UTC, hmiranda99 approved these changes

2022-06-22 02:31 UTC, gustavodesantana approved these changes

2022-06-22 02:32 UTC, garcia235 approved these changes

2022-06-22 02:56 UTC, merged