Feat/editar-perfil-aluno
kvlsndkf/project pull request #91
Opened 2022-06-20 19:57 UTC by Palominha

## O que está sendo feito:

* Estilização da pagina de editar do perfil de aluno.

2022-06-23 01:57 UTC, hmiranda99 requested changes
## Pontos vistos

### Botão editar
- O botão aparenta estar mais grosso do que o padrão
- A cor dele e largura estão diferentes do protótipo
- Não tem o local onde mostra o nome do arquivo enviado
- Botão está sme hover

*Como está*
![image](https://user-images.githubusercontent.com/79329906/175189935-59263a2c-bf03-4ae7-88b9-d2dcdbf8a5ad.png)

*Como deve ser*
![image](https://user-images.githubusercontent.com/79329906/175189970-42d1e1b3-2d24-42e8-8838-0ec8f48e8380.png)

##
### Favi-con
- A página está sem o fav-icon

##
### Inputs
- Os tamanhos dos inputs estão completamente fora do padrão
- Só o select q está

*Como está*
![image](https://user-images.githubusercontent.com/79329906/175190281-f6141d58-2a23-4e2a-88d0-b1d0eb40cf69.png)

*Como deve ser*
![image](https://user-images.githubusercontent.com/79329906/175190268-2cb93811-7982-4eba-ad2c-c0fab31b7db5.png)

##
### Acordeon
- Os acordeons também não estão parecidos com o do protótipo
- Estão parecendo inputs gigantes
- Já os inputs daqui também estão bem fora do padrão, só que pequenos

*Como está*
![image](https://user-images.githubusercontent.com/79329906/175190505-322b7111-b525-4705-8335-05003096cac9.png)

*Como é*
![image](https://user-images.githubusercontent.com/79329906/175190445-3cd673a1-738b-491d-a3f7-b7f2bc46370d.png)

##
### Botões do rodapé
- Estão sem hover
- A distância entre eles está maior do que está no protótipo
- Quando aperta em cancelar não acontece nada

2022-06-23 02:07 UTC, emillienicole reviewed
RCs pedidos que foram resolvidos:

Texto botão de atualizar centralizado ✅
Alert de erro aparecendo sem quebrar layout ✅ 

> No aguardo da resolução das RCs da Helena

2022-06-23 14:08 UTC, emillienicole reviewed
Como a Helena está ocupada, vou revisar as RCs pedidas pra adiantar

- Botão de atualizar foto continua grosso
- Botões sem hover
- O accordion do link e senha são separados como está em QA, não faz sentido ser um dentro do outro
- O local não aparece abaixo do botão quando clicamos (nome da foto selecionada)

2022-06-24 01:37 UTC, hmiranda99 requested changes
## Pontos vistos

- Os inputs ainda estão diferentes do padrão, olhe no cadastro do aluno para pegar o estiilo igual;
- A seta dos acordeons estão pretas;
- A label do primeiro acordeon está diferente da dos outros, tanto em tamanho quanto em peso.
- Esse divider que você colocou no primeiro acordeon na parte de cima e na debaixo, é o divider nativo do acordeon que foi o que estáva na tela sem estilo, todos devem ter para que tenha uma divisão, mas deve ser o divider do acordeon.
- O primeiro acordeon está aberto, só está aberto no protótipo para o front saber como é dentro, ele não deve estar aberto.
- O botão de enviar a foto continua sem o nome do arquivo.

2022-06-25 21:16 UTC, emillienicole requested changes
- O botão de cancelar não faz nada
- Pretende colocar o texto do arquivo selecionado?
- Não tem link e hover certo no item "seguindo" (tanto desktop como responsividade)
- Não deve ter mais o item "notificações" no menu responsivo
-

2022-06-27 04:26 UTC, hmiranda99 approved these changes

2022-06-27 04:27 UTC, emillienicole approved these changes

2022-06-27 04:28 UTC, merged